# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Meteora' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Meteora

  target 'MeteoraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeteoraUITests' do
    # Pods for testing
  end

pod 'HDAugmentedReality', '~> 3.0'
pod 'SDWebImage', '~> 5.0'
end
